import type { NextPage } from "next";
import Head from "next/head";
import PollCard from "../components/PollCard";
import axios from "axios";
import useSWR from "swr";
import LoadingPollCard from "../components/LoadingPollCard";

const fetcher = (url: string) => axios.get(url).then((res) => res.data);

const Home: NextPage = () => {
  const { data, error } = useSWR("/api/poll", fetcher);
  return (
    <div>
      <Head>
        <title>Home - Voting App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {error ? (
        <div>Failed to load</div>
      ) : (
        <div>
          {!data && !error ? <LoadingPollCard /> : ""}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-20">
            {data &&
              data.map((item: any, index: any) => (
                <PollCard
                  key={index}
                  title={item.title}
                  author={item.author.username}
                  options={item.options}
                />
              ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default Home;
