import type {NextPage, GetServerSideProps, InferGetServerSidePropsType} from 'next'
import {connectDatabase} from '../utils/connectDatabase'
import Head from 'next/head'
import PollCard from "../components/PollCard";

export const getServerSideProps: GetServerSideProps = async () => {
    const db = await connectDatabase()
    const votings = await db
        .collection('voting')
        .find({})
        .toArray()
    return {
        props: {
            votings: JSON.parse(JSON.stringify(votings))
        }
    }
}

const Home: NextPage = ({votings}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
    return (
        <div>
            <Head>
                <title>Home - Voting App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-20">
                {votings && votings.map((item: any, index: any) => (
                    <PollCard key={index} title={item.title}/>
                ))}
            </div>
        </div>
    )
}

export default Home
