import type {NextPage} from 'next'
import Head from 'next/head'
import {useRouter} from 'next/router'
import {useContext, useState} from 'react'
import axios from 'axios'
import AuthContext from '../utils/AuthContext'

const Login: NextPage = () => {
    const router = useRouter()
    const {setAuthContext} = useContext(AuthContext)
    const [username, setUsername] = useState<string>('');
    const [password, setPassword] = useState('')
    const [processing, setProcessing] = useState(false)
    const [errorMessage, setErrorMessage] = useState(null)

    const submit = async (e: { preventDefault: () => void; }) => {
        e.preventDefault()
        setProcessing(true)
        try {
            const response = await axios.post('/api/login', {
                username,
                password
            })
            setProcessing(false)
            setAuthContext(response.data.username)
            localStorage.setItem('username', response.data.username)
            alert(response.data.message)
            await router.push('/')
        } catch (e) {
            setErrorMessage(e.response.data.message)
            setProcessing(false)
        }
    }

    return (
        <>
            <Head>
                <title>Login - Voting App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <form className="shadow-lg rounded max-w-md justify-between mx-auto px-4 py-6">
                <h3 className="text-lg font-semibold mb-4">Login</h3>
                <div
                    className={!errorMessage ? 'hidden' : '' + 'text-red-800 bg-red-300 py-4 px-3 font-semibold rounded my-4'}>{errorMessage}</div>
                <label>
                    <span className="block mb-2">Username</span>
                    <input value={username} onChange={(e) => setUsername(e.target.value)} type="text"
                           className="block w-full border border-gray-300 py-2 px-3 rounded" id="username"
                           name="username"/>
                </label>
                <label>
                    <span className="block my-2">Password</span>
                    <input value={password} onChange={(e) => setPassword(e.target.value)} type="password"
                           className="block w-full border border-gray-300 py-2 px-3 rounded"
                           id="password"
                           name="password"/>
                </label>
                <button
                    onClick={submit}
                    className="mt-4 bg-gray-300 hover:bg-gray-400 text-gray-800 px-4 py-2 rounded focus:outline-none font-semibold">
                    <span className={!processing ? 'hidden' : ''}>Processing...</span>
                    <span className={processing ? 'hidden' : ''}>Login</span>
                </button>
            </form>
        </>
    );
};

export default Login;